# Generated by Django 4.2.7 on 2024-06-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='name_enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.enseignant'),
        ),
    ]
