# Generated by Django 5.0.6 on 2024-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_alter_ue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
