# Generated by Django 4.1 on 2024-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Absences', '0002_absence_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='enseignant_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
