<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-07 12:38
=======
# Generated by Django 4.2.7 on 2024-06-11 07:49
>>>>>>> 5bdf2b3663d5f5787b3391e31a0301388388747f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
