# Generated by Django 5.0.6 on 2024-05-31 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ENSISmart", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Absence",
        ),
    ]
