# Generated by Django 5.0.6 on 2024-06-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mail',
            new_name='email',
        ),
    ]
