# Generated by Django 5.0.6 on 2024-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_etudiant', models.CharField(max_length=100)),
                ('NOM', models.CharField(max_length=100)),
                ('Prénom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
