# Generated by Django 5.0.6 on 2024-06-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0002_rename_mail_utilisateur_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='utilisateur_ptr',
        ),
        migrations.RemoveField(
            model_name='note',
            name='enseignant',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
