# Generated by Django 4.1 on 2024-06-04 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ENSISmart", "0002_enseignant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eleve",
            old_name="email",
            new_name="email_eleve",
        ),
        migrations.RenameField(
            model_name="enseignant",
            old_name="email",
            new_name="email_enseignant",
        ),
    ]
