# Generated by Django 5.0.6 on 2024-06-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0002_eleve2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleve2',
        ),
    ]
