# Generated by Django 5.0.6 on 2024-05-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENSISmart", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events_vie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Calendar Events",
                "verbose_name_plural": "Calendar Events",
            },
        ),
    ]
