# Generated by Django 4.1 on 2024-06-04 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ENSISmart", "0003_rename_email_eleve_email_eleve_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eleve",
            old_name="email_eleve",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="enseignant",
            old_name="email_enseignant",
            new_name="email",
        ),
    ]
