# Generated by Django 4.1 on 2024-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENSISmart", "0004_rename_email_eleve_eleve_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="enseignant",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
    ]
