# Generated by Django 4.2.7 on 2024-06-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0005_eleve_first_login_enseignant_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='first_login',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='first_login',
        ),
        migrations.AddField(
            model_name='eleve',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$8FscyDENwnUqPB1SQXzBr7$8aCiUq1V3mOsbbADsWA2USCOHSFrLFNwBEfplyN/zb4=', max_length=30),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$MJi4YCsQzhuZsQwwEOsiLT$P4m52W1cMl2dLwVQAXXy/18IsEHu0L5Ys9XTSenXdKQ=', max_length=30),
        ),
    ]
