# Generated by Django 5.0.6 on 2024-06-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0005_absence_eleve_delete_events_vie_absence_eleve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='event',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
