# Generated by Django 4.1 on 2024-06-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENSISmart", "0006_temporarylink_user_remove_eleve_first_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$3uU6Bo574J9PyMExlrOxiY$rQOJC9Y4zmgWBODz2/JKN9KSjwM8HoCokbMXzEzUt8E=",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="enseignant",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$mCOex12t7f0NBSBjp4U4e1$4Rvf9bk33eCW4j+l81TKdCg2zbZBrfRKXV+ZFV15nOk=",
                max_length=30,
            ),
        ),
    ]
