# Generated by Django 4.1 on 2024-06-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENSISmart", "0007_alter_eleve_password_alter_enseignant_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$Dlf0MWF5B20O8KeGGeLJpG$6G8mBWpdgGE7wDEB1qKMam9LKBkSHTP1yv/e2IlsILI=",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="enseignant",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$PLS6p4IkRka6b9udgLhNeX$iT8eKEeQG/QUMZdn+LNmdebKSGxEw22HcC8E48TrhC0=",
                max_length=30,
            ),
        ),
    ]
