# Generated by Django 4.2.7 on 2024-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0008_alter_eleve_password_alter_enseignant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$vfVVIOe0ruRPIAGMZX7RLA$2OsubSEeyQCicEkw6cEX5CZI1+nLHSVeUL9OoznEaoU=', max_length=30),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$KMUIRZ8F6EcEeFAerpk4xb$S8uBKo0aC9x6ee9NYzGxKvnxtRwKb/JXcTkYcgPfOwk=', max_length=30),
        ),
    ]
