# Generated by Django 4.2.7 on 2024-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0009_alter_eleve_password_alter_enseignant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$UnJlnYo3fbBVWzHItsnicF$kaqpBO7yrthaAb2o0iwXBjTk3KNUezos2JB6wbnI3cc=', max_length=30),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sdw9QJchGSl5fP6c5mlUur$/lAclVwXxt0Py1WccmUk2HI8ZzFCbJAHU4cvbDmIFUI=', max_length=30),
        ),
    ]
