# Generated by Django 4.2.7 on 2024-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0010_alter_eleve_password_alter_enseignant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$tTnGLHFd0bsifUdgqAkbTM$+hP0V7OA0iXnbR9A2hAbdkQifmhhWE7Yia/Fv8vXPBc=', max_length=30),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$VxGlsJorJyXNmsn49VPhiV$O/9UqyDFEk0k7V0QTMlb4ZBhVlBhPCFc5uKii6UIXKM=', max_length=30),
        ),
    ]
