# Generated by Django 4.1 on 2024-06-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ENSISmart", "0011_alter_eleve_password_alter_enseignant_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$uGb0WAKWGPiktOITUQrY3i$gLyRgqQf+2GJIG634nPDXvqsr/0Icv7Dot8X/JR/BqU=",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="enseignant",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$390000$vYpQtfLrEQeea4ETvxUivO$coDzbCrWgGCyylnj0Bj+1vRt5wv8LKYurI6VXTzcZnY=",
                max_length=30,
            ),
        ),
    ]
