# Generated by Django 4.2.7 on 2024-06-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENSISmart', '0012_alter_eleve_password_alter_enseignant_password'),
        ('ENSISmart', '0012_eleve_is_first_co_enseignant_is_first_co_and_more'),
    ]

    operations = [
    ]
