# Generated by Django 5.0.6 on 2024-06-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='enseignant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.enseignant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
