# Generated by Django 4.1 on 2024-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
