# Generated by Django 4.1 on 2024-06-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='TP',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='matiere',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='TD',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(to='User.matiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('eleve', 'matiere')},
        ),
        migrations.RemoveField(
            model_name='note',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='note',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='enseignant',
        ),
    ]
