# Generated by Django 4.2.7 on 2024-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_administrateur_email_alter_administrateur_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='is_first_co',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='is_first_co',
            field=models.BooleanField(default=True),
        ),
    ]
