# Generated by Django 5.0.6 on 2024-06-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_administrateur_id_alter_administrateur_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
