# Generated by Django 5.0.6 on 2024-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_enseignant_is_first_co_enseignant_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
