# Generated by Django 5.0.6 on 2024-06-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_note_enseignant_alter_note_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='note',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='enseignant',
        ),
        migrations.AlterField(
            model_name='note',
            name='eleve',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.eleve'),
        ),
    ]
