# Generated by Django 5.0.6 on 2024-06-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_administrateur_email_alter_administrateur_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
