# Generated by Django 4.1 on 2024-06-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_note_coefficient_remove_note_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
