# Generated by Django 5.0.6 on 2024-06-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_eleve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
