# Generated by Django 5.0.6 on 2024-06-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_enseignant_id'),
        ('User', '0004_alter_eleve_id'),
    ]

    operations = [
    ]
